AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple subents'

Parameters:
  VpcId:
    Description: VPC Id
    Type: AWS::EC2::VPC::Id

  PrivateSubnet1CIDR:
    Description: IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24

  PrivateSubnet2CIDR:
    Description: IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24

Resources:
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR


Outputs:
  PrivateSubnet1Id:
    Description: Id of the Private subent 1
    Value: !Ref PrivateSubnet1

  PrivateSubnet2Id:
    Description: Id of the Private subent 2
    Value: !Ref PrivateSubnet2