AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple VPC'

Parameters:
  VpcCIDR:
    Description: IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR

Outputs:
  VpcId:
    Description: Id of the VPC
    Value: !Ref VPC
